### ISSUE TITLE
non wikipedia links don't work

### ISSUE THREAD

**Issue by steezeburger** [steezeburger/wikipedia-browser#3]

**Comment by vr-varad** [comment]
@steezeburger Wherever I could go I could find wiki links can you please explain how to generate this issue?

**Comment by steezeburger** [comment]
@vr-varad try going to the page for Google and clicking the link to their website in the quick info section. It won't work I believe.

**Comment by vr-varad** [comment]
https://github.com/user-attachments/assets/a5d166be-c01a-466d-a87c-e75fd8090299

I think its working i did it with google and then with netflix

**Comment by vr-varad** [comment]
@steezeburger

**Comment by steezeburger** [comment]
Oh nice! What about the references at the bottom? Can you click around a bunch of other links on the page to see if there's another type that is still broken? It's possible the issue has been fixed though. I'm traveling right now, but I will check on this tonight and close it if it's fixed! 🙏

**Comment by steezeburger** [comment]
I found the original issue. Links at the bottom of the homepage won't open, like the link to "MediaWiki" and the other sister projects.

**Comment by vr-varad** [comment]
@steezeburger I will look into it.

**Comment by steezeburger** [comment]
Closed by #10
