### ISSUE TITLE
user should be able to open images

### ISSUE THREAD

**Issue by steezeburger** [steezeburger/wikipedia-browser#6]

**Comment by vr-varad** [comment]
hey @steezeburger can i give it a shot?

**Comment by steezeburger** [comment]
@vr-varad that would be great! I am going to refactor the app architect, but I don't think that would affect this work. Feel free to fork this repo and open a pull request!

**Comment by steezeburger** [comment]
I've reorganized the app a little bit here https://github.com/steezeburger/wikipedia-browser/pull/7

For this issue, you'll probably need to change how `handleLinkClick` works here https://github.com/steezeburger/wikipedia-browser/blob/main/web/src/components/WikipediaBrowser/WikipediaBrowser.tsx#L54

Also, the work done for this issue will likely be similar to https://github.com/steezeburger/wikipedia-browser/issues/3. You might be able to fix both these.

**Comment by vr-varad** [comment]
I was able to get the image but currently, I am working on why the main page goes to http://localhost:3000/wiki/File:something.jpg
